sudo: required
dist: trusty
language: node_js
node_js: '8'
install: npm install
deploy:
  provider: heroku
  api_key:
    secure: b6a99335-aa23-49e9-8130-4e04ef9c0b73
  app: color-it
  on:
    all_branches: true
run: npm install && npm run start-heroku
scripts:
- scp -i color-it.pem public/sw.js root@color-it.online:/home/ubuntu/color-it-frontend/public
before_install:
- openssl aes-256-cbc -K $encrypted_dd5ca86accb9_key -iv $encrypted_dd5ca86accb9_iv
  -in color-it.pem.enc -out color-it.pem -d
