sudo: required
dist: trusty
language: node_js
node_js: "8"
install: npm install

#branches: travis

deploy: 
  provider: heroku
  api_key:
    secure: b6a99335-aa23-49e9-8130-4e04ef9c0b73
  app: color-it
  on:
    all_branches: true
run: npm install && npm run start